spring:
  application:
    name: messagebushttpserver

server:
  port: 8350

logging:
  level:
    root: DEBUG
    
messagebus:
  pubsuberHost: 127.0.0.1
  pubsuberPort: 6379
  messagebuspool:
    maxtotal: 200